# action.yml
name: "MatosSphere GitHub Action"
description: "Run MatosSphere scan against IaC projects"
author: 'Cloudmatos'
branding:
  icon: "shield"
  color: "green"
inputs:
  scan_dir:
    description: 'scan_dir'
    required: true
  api_key:
    description: 'api_key'
    required: true
  server_url:
    description: 'Server URL'
    default: 'https://app-api-cnapp.cloudmatos.ai'
    required: false
  username:
    description: 'Username'
    required: false
  password:
    description: 'Password'
    required: false
  docker_network:
    description: 'Docker Network ID'
    default: ${{ job.container.network }}
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'